final countries = [
  {"country": "Afeganistão", "iso": "AF", "ddi": "+93", "emoji": "🇦🇫", "pattern": "+93 X XXX XXXX"},
  {"country": "África do Sul", "iso": "ZA", "ddi": "+27", "emoji": "🇿🇦", "pattern": "+27 XXX XXX XXX"},
  {"country": "Albânia", "iso": "AL", "ddi": "+355", "emoji": "🇦🇱", "pattern": "+355 X XXX XXX"},
  {"country": "Alemanha", "iso": "DE", "ddi": "+49", "emoji": "🇩🇪", "pattern": "+49 XXXX XXXXXX"},
  {"country": "Andorra", "iso": "AD", "ddi": "+376", "emoji": "🇦🇩", "pattern": "+376 XXX XXX"},
  {"country": "Angola", "iso": "AO", "ddi": "+244", "emoji": "🇦🇴", "pattern": "+244 XXX XXX XXX"},
  {"country": "Anguilla", "iso": "AI", "ddi": "+1 264", "emoji": "🇦🇮", "pattern": "+1 264 XXX XXXX"},
  {"country": "Antarctica", "iso": "AQ", "ddi": "+672", "emoji": "🇦🇶", "pattern": "+672 X XXX XXXX"},
  {"country": "Antígua e Barbuda", "iso": "AG", "ddi": "+1 268", "emoji": "🇦🇬", "pattern": "+1 268 XXX XXXX"},
  {"country": "Argentina", "iso": "AR", "ddi": "+54", "emoji": "🇦🇷", "pattern": "+54 9 XXX XXX XXX"},
  {"country": "Argélia", "iso": "DZ", "ddi": "+213", "emoji": "🇩🇿", "pattern": "+213 XX XX XX XX"},
  {"country": "Arménia", "iso": "AM", "ddi": "+374", "emoji": "🇦🇲", "pattern": "+374 XX XXX XXX"},
  {"country": "Aruba", "iso": "AW", "ddi": "+297", "emoji": "🇦🇼", "pattern": "+297 XXX XXX"},
  {"country": "Arábia Saudita", "iso": "SA", "ddi": "+966", "emoji": "🇸🇦", "pattern": "+966 X XXX XXXX"},
  {"country": "Austrália", "iso": "AU", "ddi": "+61", "emoji": "🇦🇺", "pattern": "+61 X XXXX XXXX"},
  {"country": "Áustria", "iso": "AT", "ddi": "+43", "emoji": "🇦🇹", "pattern": "+43 X XXX XXX"},
  {"country": "Azerbaijão", "iso": "AZ", "ddi": "+994", "emoji": "🇦🇿", "pattern": "+994 XX XXX XXX"},
  {"country": "Bahamas", "iso": "BS", "ddi": "+1 242", "emoji": "🇧🇸", "pattern": "+1 242 XXX XXXX"},
  {"country": "Bahrein", "iso": "BH", "ddi": "+973", "emoji": "🇧🇭", "pattern": "+973 XXX XXXX"},
  {"country": "Bangladesh", "iso": "BD", "ddi": "+880", "emoji": "🇧🇩", "pattern": "+880 X XXX XXXX"},
  {"country": "Barbados", "iso": "BB", "ddi": "+1 246", "emoji": "🇧🇧", "pattern": "+1 246 XXX XXXX"},
  {"country": "Bélgica", "iso": "BE", "ddi": "+32", "emoji": "🇧🇪", "pattern": "+32 X XXX XXX"},
  {"country": "Belize", "iso": "BZ", "ddi": "+501", "emoji": "🇧🇿", "pattern": "+501 XXX XXXX"},
  {"country": "Benim", "iso": "BJ", "ddi": "+229", "emoji": "🇧🇯", "pattern": "+229 XX XX XX"},
  {"country": "Bermuda", "iso": "BM", "ddi": "+1 441", "emoji": "🇧🇲", "pattern": "+1 441 XXX XXXX"},
  {"country": "Butão", "iso": "BT", "ddi": "+975", "emoji": "🇧🇹", "pattern": "+975 X XXX XXXX"},
  {"country": "Bielorrússia", "iso": "BY", "ddi": "+375", "emoji": "🇧🇾", "pattern": "+375 XX XXX XXXX"},
  {"country": "Bolívia", "iso": "BO", "ddi": "+591", "emoji": "🇧🇴", "pattern": "+591 X XXX XXXX"},
  {"country": "Bósnia e Herzegovina", "iso": "BA", "ddi": "+387", "emoji": "🇧🇦", "pattern": "+387 XX XXX XXX"},
  {"country": "Botswana", "iso": "BW", "ddi": "+267", "emoji": "🇧🇼", "pattern": "+267 XXX XXX"},
  {"country": "Brasil", "iso": "BR", "ddi": "+55", "emoji": "🇧🇷", "pattern": "+55 XX XXXXX-XXXX"},
  {"country": "Brunei", "iso": "BN", "ddi": "+673", "emoji": "🇧🇳", "pattern": "+673 XXX XXXX"},
  {"country": "Bulgária", "iso": "BG", "ddi": "+359", "emoji": "🇧🇬", "pattern": "+359 X XXX XXXX"},
  {"country": "Burkina Faso", "iso": "BF", "ddi": "+226", "emoji": "🇧🇫", "pattern": "+226 XX XX XX"},
  {"country": "Myanmar (Burma)", "iso": "MM", "ddi": "+95", "emoji": "🇲🇲", "pattern": "+95 X XXX XXX"},
  {"country": "Burundi", "iso": "BI", "ddi": "+257", "emoji": "🇧🇮", "pattern": "+257 X XX XX"},
  {"country": "Camarões", "iso": "CM", "ddi": "+237", "emoji": "🇨🇲", "pattern": "+237 XX XXX XXX"},
  {"country": "Cabo Verde", "iso": "CV", "ddi": "+238", "emoji": "🇨🇻", "pattern": "+238 X XX XX XX"},
  {"country": "Camboja", "iso": "KH", "ddi": "+855", "emoji": "🇰🇭", "pattern": "+855 XX XXX XXX"},
  {"country": "Canadá", "iso": "CA", "ddi": "+1", "emoji": "🇨🇦", "pattern": "+1 XXX XXX XXXX"},
  {"country": "Catar", "iso": "QA", "ddi": "+974", "emoji": "🇶🇦", "pattern": "+974 XXX XXXX"},
  {"country": "Chad", "iso": "TD", "ddi": "+235", "emoji": "🇹🇩", "pattern": "+235 XX XX XX"},
  {"country": "Chile", "iso": "CL", "ddi": "+56", "emoji": "🇨🇱", "pattern": "+56 X XXX XXX"},
  {"country": "China", "iso": "CN", "ddi": "+86", "emoji": "🇨🇳", "pattern": "+86 XXXX XXXXXX"},
  {"country": "Chipre", "iso": "CY", "ddi": "+357", "emoji": "🇨🇾", "pattern": "+357 X XXX XXX"},
  {"country": "Christmas Island", "iso": "CX", "ddi": "+61", "emoji": "🇨🇽", "pattern": "+61 X XXXX XXXX"},
  {"country": "Cingapura", "iso": "SG", "ddi": "+65", "emoji": "🇸🇬", "pattern": "+65 XXXX XXXX"},
  {"country": "Colômbia", "iso": "CO", "ddi": "+57", "emoji": "🇨🇴", "pattern": "+57 X XXX XXXX"},
  {"country": "Comores", "iso": "KM", "ddi": "+269", "emoji": "🇰🇲", "pattern": "+269 XX XX XX"},
  {"country": "Coreia do Norte", "iso": "KP", "ddi": "+850", "emoji": "🇰🇵", "pattern": "+850 XXX XXXX"},
  {"country": "Coreia do Sul", "iso": "KR", "ddi": "+82", "emoji": "🇰🇷", "pattern": "+82 X XXX XXXX"},
  {"country": "Costa do Marfim", "iso": "CI", "ddi": "+225", "emoji": "🇨🇮", "pattern": "+225 XX XX XX"},
  {"country": "Costa Rica", "iso": "CR", "ddi": "+506", "emoji": "🇨🇷", "pattern": "+506 XXX XXXX"},
  {"country": "Croácia", "iso": "HR", "ddi": "+385", "emoji": "🇭🇷", "pattern": "+385 XX XXX XXX"},
  {"country": "Cuba", "iso": "CU", "ddi": "+53", "emoji": "🇨🇺", "pattern": "+53 X XXX XXXX"},
  {"country": "Curaçao", "iso": "CW", "ddi": "+599", "emoji": "🇨🇼", "pattern": "+599 XXX XXX"},
  {"country": "Dinamarca", "iso": "DK", "ddi": "+45", "emoji": "🇩🇰", "pattern": "+45 XX XX XX"},
  {"country": "Dominica", "iso": "DM", "ddi": "+1 767", "emoji": "🇩🇲", "pattern": "+1 767 XXX XXXX"},
  {"country": "Egito", "iso": "EG", "ddi": "+20", "emoji": "🇪🇬", "pattern": "+20 X XXX XXXX"},
  {"country": "El Salvador", "iso": "SV", "ddi": "+503", "emoji": "🇸🇻", "pattern": "+503 XXX XXXX"},
  {"country": "Equador", "iso": "EC", "ddi": "+593", "emoji": "🇪🇨", "pattern": "+593 X XXX XXXX"},
  {"country": "Espanha", "iso": "ES", "ddi": "+34", "emoji": "🇪🇸", "pattern": "+34 XXX XXX XXX"},
  {"country": "Estados Unidos", "iso": "US", "ddi": "+1", "emoji": "🇺🇸", "pattern": "+1 XXX XXX XXXX"},
  {"country": "Estônia", "iso": "EE", "ddi": "+372", "emoji": "🇪🇪", "pattern": "+372 XXX XXX"},
  {"country": "Eswatini", "iso": "SZ", "ddi": "+268", "emoji": "🇸🇿", "pattern": "+268 XXX XXXX"},
  {"country": "Eslováquia", "iso": "SK", "ddi": "+421", "emoji": "🇸🇰", "pattern": "+421 XXX XXX XXX"},
  {"country": "Eslovênia", "iso": "SI", "ddi": "+386", "emoji": "🇸🇮", "pattern": "+386 X XXX XXX"},
  {"country": "Estados Federados da Micronésia", "iso": "FM", "ddi": "+691", "emoji": "🇫🇲", "pattern": "+691 XXX XXXX"},
  {"country": "Ilhas Falkland", "iso": "FK", "ddi": "+500", "emoji": "🇫🇰", "pattern": "+500 XXX XXX"},
  {"country": "Ilhas Faroe", "iso": "FO", "ddi": "+298", "emoji": "🇫🇴", "pattern": "+298 XXX XXX"},
  {"country": "Filipinas", "iso": "PH", "ddi": "+63", "emoji": "🇵🇭", "pattern": "+63 X XXX XXXX"},
  {"country": "Finlândia", "iso": "FI", "ddi": "+358", "emoji": "🇫🇮", "pattern": "+358 XX XXX XXX"},
  {"country": "França", "iso": "FR", "ddi": "+33", "emoji": "🇫🇷", "pattern": "+33 X XX XX XX XX"},
  {"country": "Gabão", "iso": "GA", "ddi": "+241", "emoji": "🇲🇬", "pattern": "+241 XX XX XX"},
  {"country": "Gâmbia", "iso": "GM", "ddi": "+220", "emoji": "🇲🇬", "pattern": "+220 XXX XXXX"},
  {"country": "Gana", "iso": "GH", "ddi": "+233", "emoji": "🇲🇬", "pattern": "+233 X XXX XXXX"},
  {"country": "Geórgia", "iso": "GE", "ddi": "+995", "emoji": "🇲🇬", "pattern": "+995 XXX XXX XXX"},
  {"country": "Gibraltar", "iso": "GI", "ddi": "+350", "emoji": "🇲🇬", "pattern": "+350 XXX XXX"},
  {"country": "Granada", "iso": "GD", "ddi": "+1 473", "emoji": "🇲🇬", "pattern": "+1 473 XXX XXXX"},
  {"country": "Grécia", "iso": "GR", "ddi": "+30", "emoji": "🇲🇬", "pattern": "+30 X XXX XXXX"},
  {"country": "Groenlândia", "iso": "GL", "ddi": "+299", "emoji": "🇲🇬", "pattern": "+299 XXX XXX"},
  {"country": "Guadalupe", "iso": "GP", "ddi": "+590", "emoji": "🇲🇬", "pattern": "+590 X XX XX XX"},
  {"country": "Guam", "iso": "GU", "ddi": "+1 671", "emoji": "🇲🇬", "pattern": "+1 671 XXX XXXX"},
  {"country": "Guatemala", "iso": "GT", "ddi": "+502", "emoji": "🇲🇬", "pattern": "+502 X-XXX-XXXX"},
  {"country": "Guiné", "iso": "GN", "ddi": "+224", "emoji": "🇲🇬", "pattern": "+224 X XX XX XX"},
  {"country": "Guiné-Bissau", "iso": "GW", "ddi": "+245", "emoji": "🇲🇬", "pattern": "+245 XX XX XX"},
  {"country": "Guiné Equatorial", "iso": "GQ", "ddi": "+240", "emoji": "🇲🇬", "pattern": "+240 XXX XXX XXX"},
  {"country": "Guyana", "iso": "GY", "ddi": "+592", "emoji": "🇲🇬", "pattern": "+592 XXX XXXX"},
  {"country": "Haiti", "iso": "HT", "ddi": "+509", "emoji": "🇲🇬", "pattern": "+509 XXX XXXX"},
  {"country": "Holanda", "iso": "NL", "ddi": "+31", "emoji": "🇲🇬", "pattern": "+31 XX XXX XXXX"},
  {"country": "Hong Kong", "iso": "HK", "ddi": "+852", "emoji": "🇲🇬", "pattern": "+852 XXXX XXXX"},
  {"country": "Hungria", "iso": "HU", "ddi": "+36", "emoji": "🇲🇬", "pattern": "+36 XX XXX XXX"},
  {"country": "Iémen", "iso": "YE", "ddi": "+967", "emoji": "🇲🇬", "pattern": "+967 X XXX XXXX"},
  {"country": "Ilha Bouvet", "iso": "BV", "ddi": "+47", "emoji": "🇲🇬", "pattern": "+47 X XXX XXXX"},
  {"country": "Ilha Heard e Ilhas McDonald", "iso": "HM", "ddi": "+61", "emoji": "🇲🇬", "pattern": "+61 X XXXX XXXX"},
  {"country": "Ilhas Malvinas", "iso": "FK", "ddi": "+500", "emoji": "🇲🇬", "pattern": "+500 XXX XXX"},
  {"country": "Ilhas Solomon", "iso": "SB", "ddi": "+677", "emoji": "🇲🇬", "pattern": "+677 X XXX XX"},
  {"country": "Ilhas Turcas e Caicos", "iso": "TC", "ddi": "+1 649", "emoji": "🇲🇬", "pattern": "+1 649 XXX XXXX"},
  {"country": "Ilhas Virgens Britânicas", "iso": "VG", "ddi": "+1 284", "emoji": "🇲🇬", "pattern": "+1 284 XXX XXXX"},
  {"country": "Ilhas Virgens Americanas", "iso": "VI", "ddi": "+1 340", "emoji": "🇲🇬", "pattern": "+1 340 XXX XXXX"},
  {"country": "Ilhas Wallis e Futuna", "iso": "WF", "ddi": "+681", "emoji": "🇲🇬", "pattern": "+681 XX XX XX"},
  {"country": "Índia", "iso": "IN", "ddi": "+91", "emoji": "🇮🇳", "pattern": "+91 XXXXX XXXXX"},
  {"country": "Indonésia", "iso": "ID", "ddi": "+62", "emoji": "🇮🇩", "pattern": "+62 X-XXXX-XXXX"},
  {"country": "Irã", "iso": "IR", "ddi": "+98", "emoji": "🇮🇷", "pattern": "+98 XXX XXX XXXX"},
  {"country": "Iraque", "iso": "IQ", "ddi": "+964", "emoji": "🇮🇶", "pattern": "+964 XXX XXX XXXX"},
  {"country": "Irlanda", "iso": "IE", "ddi": "+353", "emoji": "🇮🇪", "pattern": "+353 X XXX XXXX"},
  {"country": "Islândia", "iso": "IS", "ddi": "+354", "emoji": "🇮🇸", "pattern": "+354 XXX XXX0"},
  {"country": "Itália", "iso": "IT", "ddi": "+39", "emoji": "🇮🇹", "pattern": "+39 XXX XXX XXX"},
  {"country": "Jamaica", "iso": "JM", "ddi": "+1 876", "emoji": "🇯🇲", "pattern": "+1 876 XXX XXXX"},
  {"country": "Japão", "iso": "JP", "ddi": "+81", "emoji": "🇯🇵", "pattern": "+81 XX-XXXX-XXXX"},
  {"country": "Jordânia", "iso": "JO", "ddi": "+962", "emoji": "🇯🇴", "pattern": "+962 7XX XXX XXX"},
  {"country": "Kazakhstan", "iso": "KZ", "ddi": "+7", "emoji": "🇰🇿", "pattern": "+7 XXX XXX XXXX"},
  {"country": "Quênia", "iso": "KE", "ddi": "+254", "emoji": "🇰🇪", "pattern": "+254 X XXX XXXX"},
  {"country": "Kiribati", "iso": "KI", "ddi": "+686", "emoji": "🇰🇮", "pattern": "+686 X XXX"},
  {"country": "Kosovo", "iso": "XK", "ddi": "+383", "emoji": "🇽🇰", "pattern": "+383 XX XXX XXX"},
  {"country": "Letônia", "iso": "LV", "ddi": "+371", "emoji": "🇱🇻", "pattern": "+371 XX XXX XX"},
  {"country": "Líbano", "iso": "LB", "ddi": "+961", "emoji": "🇱🇧", "pattern": "+961 X XXX XXX"},
  {"country": "Líbia", "iso": "LY", "ddi": "+218", "emoji": "🇱🇾", "pattern": "+218 X XXX XXXX"},
  {"country": "Lituânia", "iso": "LT", "ddi": "+370", "emoji": "🇱🇹", "pattern": "+370 XXX XXX XX"},
  {"country": "Luxemburgo", "iso": "LU", "ddi": "+352", "emoji": "🇱🇺", "pattern": "+352 XX XXX XXX"},
  {"country": "Macau", "iso": "MO", "ddi": "+853", "emoji": "🇲🇴", "pattern": "+853 XXXX XXXX"},
  {"country": "Madagascar", "iso": "MG", "ddi": "+261", "emoji": "🇲🇬", "pattern": "+261 X XX XX XX"},
  {"country": "Malásia", "iso": "MY", "ddi": "+60", "emoji": "🇲🇾", "pattern": "+60 X-XXXX-XXXX"},
  {"country": "Malawi", "iso": "MW", "ddi": "+265", "emoji": "🇲🇼", "pattern": "+265 X XXX XXX"},
  {"country": "Maldivas", "iso": "MV", "ddi": "+960", "emoji": "🇲🇻", "pattern": "+960 XXX XXXX"},
  {"country": "Mali", "iso": "ML", "ddi": "+223", "emoji": "🇲🇱", "pattern": "+223 XX XX XX"},
  {"country": "Malta", "iso": "MT", "ddi": "+356", "emoji": "🇲🇹", "pattern": "+356 XX XXX XXX"},
  {"country": "Marrocos", "iso": "MA", "ddi": "+212", "emoji": "🇲🇦", "pattern": "+212 X XX XX XX"},
  {"country": "Maurício", "iso": "MU", "ddi": "+230", "emoji": "🇲🇺", "pattern": "+230 XXX XXX"},
  {"country": "Mauritânia", "iso": "MR", "ddi": "+222", "emoji": "🇲🇷", "pattern": "+222 XX XX XX"},
  {"country": "México", "iso": "MX", "ddi": "+52", "emoji": "🇲🇽", "pattern": "+52 X XXX XXXX"},
  {"country": "Mianmar", "iso": "MM", "ddi": "+95", "emoji": "🇲🇲", "pattern": "+95 X XXX XXXX"},
  {"country": "Moçambique", "iso": "MZ", "ddi": "+258", "emoji": "🇲🇿", "pattern": "+258 X XXX XXX"},
  {"country": "Mónaco", "iso": "MC", "ddi": "+377", "emoji": "🇲🇨", "pattern": "+377 X XX XX XX"},
  {"country": "Mongólia", "iso": "MN", "ddi": "+976", "emoji": "🇲🇳", "pattern": "+976 X XX XX XX"},
  {"country": "Montenegro", "iso": "ME", "ddi": "+382", "emoji": "🇲🇪", "pattern": "+382 XX XXX XXX"},
  {"country": "Namíbia", "iso": "NA", "ddi": "+264", "emoji": "🇳🇦", "pattern": "+264 X XXX XXXX"},
  {"country": "Nauru", "iso": "NR", "ddi": "+674", "emoji": "🇳🇷", "pattern": "+674 X XXX"},
  {"country": "Nepal", "iso": "NP", "ddi": "+977", "emoji": "🇳🇵", "pattern": "+977 X-XXXX-XXXX"},
  {"country": "Nicarágua", "iso": "NI", "ddi": "+505", "emoji": "🇳🇮", "pattern": "+505 XXX XXXX"},
  {"country": "Níger", "iso": "NE", "ddi": "+227", "emoji": "🇳🇪", "pattern": "+227 XX XX XX"},
  {"country": "Nigéria", "iso": "NG", "ddi": "+234", "emoji": "🇳🇬", "pattern": "+234 X XXX XXXX"},
  {"country": "Noruega", "iso": "NO", "ddi": "+47", "emoji": "🇳🇴", "pattern": "+47 XX XX XX"},
  {"country": "Nova Caledônia", "iso": "NC", "ddi": "+687", "emoji": "🇳🇨", "pattern": "+687 X XX XX"},
  {"country": "Omã", "iso": "OM", "ddi": "+968", "emoji": "🇴🇲", "pattern": "+968 X XXX XXXX"},
  {"country": "Países Baixos", "iso": "NL", "ddi": "+31", "emoji": "🇳🇱", "pattern": "+31 XX XXX XXXX"},
  {"country": "Palau", "iso": "PW", "ddi": "+680", "emoji": "🇵🇼", "pattern": "+680 X XXX XXX"},
  {"country": "Panamá", "iso": "PA", "ddi": "+507", "emoji": "🇵🇦", "pattern": "+507 X-XXX-XXXX"},
  {"country": "Papua Nova Guiné", "iso": "PG", "ddi": "+675", "emoji": "🇵🇬", "pattern": "+675 X XXX XXXX"},
  {"country": "Paquistão", "iso": "PK", "ddi": "+92", "emoji": "🇵🇰", "pattern": "+92 XXX XXX XXXX"},
  {"country": "Polônia", "iso": "PL", "ddi": "+48", "emoji": "🇵🇱", "pattern": "+48 XXX XXX XXX"},
  {"country": "Portugal", "iso": "PT", "ddi": "+351", "emoji": "🇵🇹", "pattern": "+351 XXX XXX XXX"},
  {"country": "Quiribati", "iso": "KI", "ddi": "+686", "emoji": "🇰🇮", "pattern": "+686 X XXX"},
  {"country": "República Centro-Africana", "iso": "CF", "ddi": "+236", "emoji": "🇨🇫", "pattern": "+236 XX XX XX"},
  {"country": "República Dominicana", "iso": "DO", "ddi": "+1 809", "emoji": "🇩🇴", "pattern": "+1 809 XXX XXXX"},
  {"country": "República Tcheca", "iso": "CZ", "ddi": "+420", "emoji": "🇨🇿", "pattern": "+420 XXX XXX XXX"},
  {"country": "Romênia", "iso": "RO", "ddi": "+40", "emoji": "🇷🇴", "pattern": "+40 XXX XXX XXX"},
  {"country": "Ruanda", "iso": "RW", "ddi": "+250", "emoji": "🇷🇼", "pattern": "+250 X XXX XXX"},
  {"country": "Rússia", "iso": "RU", "ddi": "+7", "emoji": "🇷🇺", "pattern": "+7 XXX XXX XXXX"},
  {"country": "Saara Ocidental", "iso": "EH", "ddi": "+212", "emoji": "🇲🇦", "pattern": "+212 X XX XX XX"},
  {"country": "Saint Kitts e Nevis", "iso": "KN", "ddi": "+1 869", "emoji": "🇰🇳", "pattern": "+1 869 XXX XXXX"},
  {"country": "Saint Lucia", "iso": "LC", "ddi": "+1 758", "emoji": "🇱🇨", "pattern": "+1 758 XXX XXXX"},
  {"country": "Saint Vincent e Granadinas", "iso": "VC", "ddi": "+1 784", "emoji": "🇻🇨", "pattern": "+1 784 XXX XXXX"},
  {"country": "Samoa", "iso": "WS", "ddi": "+685", "emoji": "🇼🇸", "pattern": "+685 X XXX"},
  {"country": "San Marino", "iso": "SM", "ddi": "+378", "emoji": "🇸🇲", "pattern": "+378 X XXX XXX"},
  {"country": "Santa Lúcia", "iso": "LC", "ddi": "+1 758", "emoji": "🇱🇨", "pattern": "+1 758 XXX XXXX"},
  {"country": "Senegal", "iso": "SN", "ddi": "+221", "emoji": "🇸🇳", "pattern": "+221 XX XX XX"},
  {"country": "Serra Leoa", "iso": "SL", "ddi": "+232", "emoji": "🇸🇱", "pattern": "+232 X XXX XXX"},
  {"country": "Seychelles", "iso": "SC", "ddi": "+248", "emoji": "🇸🇨", "pattern": "+248 X XXX XXX"},
  {"country": "Singapura", "iso": "SG", "ddi": "+65", "emoji": "🇸🇬", "pattern": "+65 XXXX XXXX"},
  {"country": "Síria", "iso": "SY", "ddi": "+963", "emoji": "🇸🇾", "pattern": "+963 X XXX XXXX"},
  {"country": "Somália", "iso": "SO", "ddi": "+252", "emoji": "🇸🇴", "pattern": "+252 X XXX XXX"},
  {"country": "Sri Lanka", "iso": "LK", "ddi": "+94", "emoji": "🇱🇰", "pattern": "+94 X XXX XXX X"},
  {"country": "Suazilândia", "iso": "SZ", "ddi": "+268", "emoji": "🇸🇿", "pattern": "+268 XXX XXXX"},
  {"country": "Sudão", "iso": "SD", "ddi": "+249", "emoji": "🇸🇩", "pattern": "+249 X XXX XXX"},
  {"country": "Suriname", "iso": "SR", "ddi": "+597", "emoji": "🇸🇷", "pattern": "+597 XXX XXXX"},
  {"country": "Suécia", "iso": "SE", "ddi": "+46", "emoji": "🇸🇪", "pattern": "+46 XXX XXX XXX"},
  {"country": "Suíça", "iso": "CH", "ddi": "+41", "emoji": "🇨🇭", "pattern": "+41 XX XXX XX XX"},
  {"country": "Tailândia", "iso": "TH", "ddi": "+66", "emoji": "🇹🇭", "pattern": "+66 X XXX XXXX"},
  {"country": "Taiwan", "iso": "TW", "ddi": "+886", "emoji": "🇹🇼", "pattern": "+886 X XXX XXXX"},
  {"country": "Tajiquistão", "iso": "TJ", "ddi": "+992", "emoji": "🇹🇯", "pattern": "+992 XXX XXX XXX"},
  {"country": "Tanzânia", "iso": "TZ", "ddi": "+255", "emoji": "🇹🇿", "pattern": "+255 XXX XXX XXX"},
  {"country": "Timor-Leste", "iso": "TL", "ddi": "+670", "emoji": "🇹🇱", "pattern": "+670 X XXX XXX"},
  {"country": "Togo", "iso": "TG", "ddi": "+228", "emoji": "🇹🇬", "pattern": "+228 XX XX XX"},
  {"country": "Tonga", "iso": "TO", "ddi": "+676", "emoji": "🇹🇴", "pattern": "+676 X XX XX"},
  {"country": "Trinidad e Tobago", "iso": "TT", "ddi": "+1 868", "emoji": "🇹🇹", "pattern": "+1 868 XXX XXXX"},
  {"country": "Tunísia", "iso": "TN", "ddi": "+216", "emoji": "🇹🇳", "pattern": "+216 X XXX XXX"},
  {"country": "Turcomenistão", "iso": "TM", "ddi": "+993", "emoji": "🇹🇲", "pattern": "+993 XXX XXX XXX"},
  {"country": "Turquia", "iso": "TR", "ddi": "+90", "emoji": "🇹🇷", "pattern": "+90 XXX XXX XXX"},
  {"country": "Tuvalu", "iso": "TV", "ddi": "+688", "emoji": "🇹🇻", "pattern": "+688 X XX"},
  {"country": "Ucrânia", "iso": "UA", "ddi": "+380", "emoji": "🇺🇦", "pattern": "+380 XX XXX XXX"},
  {"country": "Uganda", "iso": "UG", "ddi": "+256", "emoji": "🇺🇬", "pattern": "+256 X XXX XXX"},
  {"country": "Uruguai", "iso": "UY", "ddi": "+598", "emoji": "🇺🇾", "pattern": "+598 X XXX XXX"},
  {"country": "Uzbequistão", "iso": "UZ", "ddi": "+998", "emoji": "🇺🇿", "pattern": "+998 XXX XXX XXXX"},
  {"country": "Vanuatu", "iso": "VU", "ddi": "+678", "emoji": "🇻🇺", "pattern": "+678 X XXX"},
  {"country": "Vaticano", "iso": "VA", "ddi": "+379", "emoji": "🇻🇦", "pattern": "+379 XXX XXX"},
  {"country": "Venezuela", "iso": "VE", "ddi": "+58", "emoji": "🇻🇪", "pattern": "+58 X-XXX-XXXX"},
  {"country": "Vietnã", "iso": "VN", "ddi": "+84", "emoji": "🇻🇳", "pattern": "+84 X XXX XXXX"},
  {"country": "Zâmbia", "iso": "ZM", "ddi": "+260", "emoji": "🇿🇲", "pattern": "+260 X XXX XXX"},
  {"country": "Zimbábue", "iso": "ZW", "ddi": "+263", "emoji": "🇿🇼", "pattern": "+263 X XXX XXX"}
];
